import { z } from 'zod';

const connectionId = z.string().uuid();
const mockOnDryRun = z.boolean().optional();

// Telegram chat IDs are integers (positive for users, negative for channels/groups).
// Channels can also be addressed by "@channelusername". Accept both shapes as strings.
const telegramChatId = z
  .string()
  .min(1)
  .max(64)
  .regex(/^(?:-?\d+|@[a-zA-Z][a-zA-Z0-9_]{4,31})$/, {
    message: 'chatId must be a numeric chat id or @username',
  });

export const TELEGRAM_PARSE_MODES = ['HTML', 'MarkdownV2'] as const;
export type TelegramParseMode = (typeof TELEGRAM_PARSE_MODES)[number];

export const telegramSendMessageConfigSchema = z.object({
  connectionId,
  chatId: telegramChatId,
  text: z.string().min(1).max(4096),
  parseMode: z.enum(TELEGRAM_PARSE_MODES).optional(),
  disableNotification: z.boolean().optional(),
  mockOnDryRun,
});
export type TelegramSendMessageConfig = z.infer<typeof telegramSendMessageConfigSchema>;

// Trigger config. By default fires on every inbound update; set chatId to filter to one
// chat. The signing secret (X-Telegram-Bot-Api-Secret-Token) is generated by us at
// activation time and registered with Telegram via setWebhook — not user-supplied.
export const telegramMessageReceivedConfigSchema = z.object({
  connectionId,
  chatId: telegramChatId.optional(),
});
export type TelegramMessageReceivedConfig = z.infer<typeof telegramMessageReceivedConfigSchema>;
