import { z } from 'zod';

const connectionId = z.string().uuid();
const mockOnDryRun = z.boolean().optional();

// Telegram chat IDs are integers (positive for users, negative for channels/groups).
// Channels can also be addressed by "@channelusername". Accept both shapes as strings.
const telegramChatId = z
  .string()
  .min(1)
  .max(64)
  .regex(/^(?:-?\d+|@[a-zA-Z][a-zA-Z0-9_]{4,31})$/, {
    message: 'chatId must be a numeric chat id or @username',
  });

export const TELEGRAM_PARSE_MODES = ['HTML', 'MarkdownV2'] as const;
export type TelegramParseMode = (typeof TELEGRAM_PARSE_MODES)[number];

export const telegramSendMessageConfigSchema = z.object({
  connectionId,
  chatId: telegramChatId,
  text: z.string().min(1).max(4096),
  parseMode: z.enum(TELEGRAM_PARSE_MODES).optional(),
  disableNotification: z.boolean().optional(),
  mockOnDryRun,
});
export type TelegramSendMessageConfig = z.infer<typeof telegramSendMessageConfigSchema>;

// Read / manage actions (S15 messaging pack).

// Media can be supplied three ways: a public URL, an existing Telegram file_id,
// or a base64 upload (multipart). `source` discriminates; refine enforces the
// matching field(s) are present.
export const TELEGRAM_MEDIA_SOURCES = ['url', 'fileId', 'upload'] as const;
export type TelegramMediaSource = (typeof TELEGRAM_MEDIA_SOURCES)[number];

// 10 MB base64 ≈ 13.3 MB string. Telegram caps photos ~10MB, documents ~50MB.
const TELEGRAM_FILE_CONTENT_MAX_LENGTH = 14_000_000;

const telegramMediaShape = {
  connectionId,
  chatId: telegramChatId,
  source: z.enum(TELEGRAM_MEDIA_SOURCES),
  url: z.string().url().max(2000).optional(),
  fileId: z.string().min(1).max(256).optional(),
  contentBase64: z.string().min(1).max(TELEGRAM_FILE_CONTENT_MAX_LENGTH).optional(),
  filename: z.string().min(1).max(255).optional(),
  caption: z.string().max(1024).optional(),
  parseMode: z.enum(TELEGRAM_PARSE_MODES).optional(),
  mockOnDryRun,
};

interface TelegramMediaInput {
  source: string;
  url?: string;
  fileId?: string;
  contentBase64?: string;
  filename?: string;
}

const telegramMediaRefine = (v: TelegramMediaInput): boolean => {
  if (v.source === 'url') return typeof v.url === 'string' && v.url.length > 0;
  if (v.source === 'fileId') return typeof v.fileId === 'string' && v.fileId.length > 0;
  return (
    typeof v.contentBase64 === 'string' &&
    v.contentBase64.length > 0 &&
    typeof v.filename === 'string' &&
    v.filename.length > 0
  );
};
const telegramMediaRefineOpts = {
  message:
    'media requires the field matching its source (url, fileId, or contentBase64 + filename)',
};

export const telegramSendPhotoConfigSchema = z
  .object(telegramMediaShape)
  .refine(telegramMediaRefine, telegramMediaRefineOpts);
export type TelegramSendPhotoConfig = z.infer<typeof telegramSendPhotoConfigSchema>;

export const telegramSendDocumentConfigSchema = z
  .object(telegramMediaShape)
  .refine(telegramMediaRefine, telegramMediaRefineOpts);
export type TelegramSendDocumentConfig = z.infer<typeof telegramSendDocumentConfigSchema>;

export const telegramEditMessageConfigSchema = z.object({
  connectionId,
  chatId: telegramChatId,
  messageId: z.number().int().positive(),
  text: z.string().min(1).max(4096),
  parseMode: z.enum(TELEGRAM_PARSE_MODES).optional(),
  mockOnDryRun,
});
export type TelegramEditMessageConfig = z.infer<typeof telegramEditMessageConfigSchema>;

export const telegramGetChatConfigSchema = z.object({
  connectionId,
  chatId: telegramChatId,
});
export type TelegramGetChatConfig = z.infer<typeof telegramGetChatConfigSchema>;

// Trigger config. By default fires on every inbound update; set chatId to filter to one
// chat. The signing secret (X-Telegram-Bot-Api-Secret-Token) is generated by us at
// activation time and registered with Telegram via setWebhook — not user-supplied.
export const telegramMessageReceivedConfigSchema = z.object({
  connectionId,
  chatId: telegramChatId.optional(),
});
export type TelegramMessageReceivedConfig = z.infer<typeof telegramMessageReceivedConfigSchema>;
