import {
  Box,
  BookText,
  Calendar,
  CheckSquare,
  CircleDot,
  Clock,
  Code2,
  CornerDownLeft,
  Database,
  FileText,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Github,
  Globe,
  HardDrive,
  Hash,
  Mail,
  MessageSquare,
  Move,
  Phone,
  Repeat2,
  Search,
  Send,
  Sheet,
  Smile,
  StickyNote,
  Tag,
  Upload,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { NodeType } from '@tietide/shared';

export const NODE_ICONS: Record<NodeType, LucideIcon> = {
  [NodeType.MANUAL_TRIGGER]: Zap,
  [NodeType.CRON_TRIGGER]: Clock,
  [NodeType.WEBHOOK_TRIGGER]: Webhook,
  [NodeType.HTTP_REQUEST]: Globe,
  [NodeType.CODE]: Code2,
  [NodeType.CONDITIONAL]: GitBranch,
  [NodeType.ITERATOR]: Repeat2,
  [NodeType.SUBWORKFLOW]: Workflow,
  [NodeType.RETURN]: CornerDownLeft,
  [NodeType.STICKY]: StickyNote,
  [NodeType.GMAIL_SEND]: Mail,
  [NodeType.GMAIL_SEARCH]: Mail,
  [NodeType.DRIVE_CREATE]: HardDrive,
  [NodeType.DRIVE_LIST]: HardDrive,
  [NodeType.SHEETS_APPEND]: Sheet,
  [NodeType.SHEETS_READ]: Sheet,
  [NodeType.DOCS_CREATE]: FileText,
  [NodeType.CALENDAR_CREATE]: Calendar,
  [NodeType.GMAIL_MESSAGE_RECEIVED]: Mail,
  [NodeType.GMAIL_LABEL_ADDED]: Mail,
  [NodeType.DRIVE_FILE_ADDED]: HardDrive,
  [NodeType.SHEETS_ROW_ADDED]: Sheet,
  [NodeType.CALENDAR_EVENT_CREATED]: Calendar,
  [NodeType.OUTLOOK_SEND]: Mail,
  [NodeType.OUTLOOK_SEARCH]: Mail,
  [NodeType.EXCEL_APPEND]: Sheet,
  [NodeType.EXCEL_READ]: Sheet,
  [NodeType.ONEDRIVE_CREATE]: HardDrive,
  [NodeType.OUTLOOK_MESSAGE_RECEIVED]: Mail,
  [NodeType.OUTLOOK_MESSAGE_FLAGGED]: Mail,
  [NodeType.ONEDRIVE_FILE_ADDED]: HardDrive,
  [NodeType.EXCEL_ROW_ADDED]: Sheet,
  [NodeType.SLACK_POST_MESSAGE]: MessageSquare,
  [NodeType.SLACK_POST_TO_CHANNEL]: Hash,
  [NodeType.SLACK_UPLOAD_FILE]: Upload,
  [NodeType.DISCORD_POST_WEBHOOK]: MessageSquare,
  [NodeType.TWILIO_SEND_SMS]: Phone,
  [NodeType.TWILIO_SEND_WHATSAPP]: Phone,
  [NodeType.TELEGRAM_SEND_MESSAGE]: Send,
  [NodeType.SLACK_MESSAGE_RECEIVED]: MessageSquare,
  [NodeType.SLACK_REACTION_ADDED]: Smile,
  [NodeType.DISCORD_MESSAGE_RECEIVED]: MessageSquare,
  [NodeType.TELEGRAM_MESSAGE_RECEIVED]: Send,
  [NodeType.TWILIO_SMS_RECEIVED]: Phone,
  [NodeType.NOTION_CREATE_PAGE]: BookText,
  [NodeType.NOTION_QUERY_DATABASE]: Search,
  [NodeType.TRELLO_CREATE_CARD]: CheckSquare,
  [NodeType.TRELLO_MOVE_CARD]: Move,
  [NodeType.AIRTABLE_CREATE_RECORD]: Database,
  [NodeType.AIRTABLE_UPDATE_RECORD]: Database,
  [NodeType.AIRTABLE_LIST_RECORDS]: Database,
  [NodeType.LINEAR_CREATE_ISSUE]: CircleDot,
  [NodeType.LINEAR_UPDATE_ISSUE_STATUS]: Tag,
  [NodeType.GITHUB_CREATE_ISSUE]: Github,
  [NodeType.GITHUB_COMMENT_ISSUE]: GitMerge,
  [NodeType.GITHUB_CREATE_PR]: GitPullRequest,
};

export const DEFAULT_NODE_ICON: LucideIcon = Box;

export const getNodeIcon = (nodeType: NodeType | string): LucideIcon =>
  NODE_ICONS[nodeType as NodeType] ?? DEFAULT_NODE_ICON;
