import {
  Box,
  BookText,
  Calendar,
  CalendarClock,
  CheckSquare,
  CircleDot,
  Clock,
  CloudUpload,
  Code2,
  CornerDownLeft,
  CreditCard,
  Database,
  FileText,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Github,
  Globe,
  HardDrive,
  Hash,
  Mail,
  Megaphone,
  MessageSquare,
  Move,
  Sparkles,
  Bot,
  Cpu,
  Phone,
  Repeat2,
  Search,
  Send,
  Sheet,
  Smile,
  StickyNote,
  Tag,
  Target,
  Trello,
  Upload,
  UserPlus,
  Users,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { NodeType } from '@tietide/shared';

export const NODE_ICONS: Record<NodeType, LucideIcon> = {
  [NodeType.MANUAL_TRIGGER]: Zap,
  [NodeType.CRON_TRIGGER]: Clock,
  [NodeType.WEBHOOK_TRIGGER]: Webhook,
  [NodeType.HTTP_REQUEST]: Globe,
  [NodeType.CODE]: Code2,
  [NodeType.CONDITIONAL]: GitBranch,
  [NodeType.ITERATOR]: Repeat2,
  [NodeType.SUBWORKFLOW]: Workflow,
  [NodeType.RETURN]: CornerDownLeft,
  [NodeType.STICKY]: StickyNote,
  [NodeType.GMAIL_SEND]: Mail,
  [NodeType.GMAIL_SEARCH]: Mail,
  [NodeType.GMAIL_GET_MESSAGE]: Mail,
  [NodeType.GMAIL_GET_ATTACHMENT]: Mail,
  [NodeType.GMAIL_MODIFY_LABELS]: Mail,
  [NodeType.GMAIL_CREATE_DRAFT]: Mail,
  [NodeType.DRIVE_CREATE]: HardDrive,
  [NodeType.DRIVE_LIST]: HardDrive,
  [NodeType.DRIVE_GET_FILE]: HardDrive,
  [NodeType.SHEETS_APPEND]: Sheet,
  [NodeType.SHEETS_READ]: Sheet,
  [NodeType.SHEETS_FIND_ROW]: Sheet,
  [NodeType.SHEETS_UPDATE_ROW]: Sheet,
  [NodeType.SHEETS_CLEAR_RANGE]: Sheet,
  [NodeType.DOCS_CREATE]: FileText,
  [NodeType.DOCS_GET]: FileText,
  [NodeType.DOCS_INSERT_TEXT]: FileText,
  [NodeType.DOCS_REPLACE_TEXT]: FileText,
  [NodeType.CALENDAR_CREATE]: Calendar,
  [NodeType.CALENDAR_LIST_EVENTS]: Calendar,
  [NodeType.CALENDAR_GET_EVENT]: Calendar,
  [NodeType.GMAIL_MESSAGE_RECEIVED]: Mail,
  [NodeType.GMAIL_LABEL_ADDED]: Mail,
  [NodeType.GMAIL_ATTACHMENT_RECEIVED]: Mail,
  [NodeType.DRIVE_FILE_ADDED]: HardDrive,
  [NodeType.DRIVE_FILE_UPDATED]: HardDrive,
  [NodeType.SHEETS_ROW_ADDED]: Sheet,
  [NodeType.CALENDAR_EVENT_CREATED]: Calendar,
  [NodeType.CALENDAR_EVENT_UPDATED]: Calendar,
  [NodeType.OUTLOOK_SEND]: Mail,
  [NodeType.OUTLOOK_SEARCH]: Mail,
  [NodeType.OUTLOOK_GET_MESSAGE]: Mail,
  [NodeType.OUTLOOK_GET_ATTACHMENT]: Mail,
  [NodeType.OUTLOOK_UPDATE_MESSAGE]: Mail,
  [NodeType.OUTLOOK_CREATE_DRAFT]: Mail,
  [NodeType.EXCEL_APPEND]: Sheet,
  [NodeType.EXCEL_READ]: Sheet,
  [NodeType.EXCEL_FIND_ROW]: Sheet,
  [NodeType.ONEDRIVE_CREATE]: HardDrive,
  [NodeType.OUTLOOK_MESSAGE_RECEIVED]: Mail,
  [NodeType.OUTLOOK_MESSAGE_FLAGGED]: Mail,
  [NodeType.ONEDRIVE_FILE_ADDED]: HardDrive,
  [NodeType.EXCEL_ROW_ADDED]: Sheet,
  [NodeType.SLACK_POST_MESSAGE]: MessageSquare,
  [NodeType.SLACK_POST_TO_CHANNEL]: Hash,
  [NodeType.SLACK_UPLOAD_FILE]: Upload,
  [NodeType.DISCORD_POST_WEBHOOK]: MessageSquare,
  [NodeType.DISCORD_REPLY_TO_COMMAND]: MessageSquare,
  [NodeType.TWILIO_SEND_SMS]: Phone,
  [NodeType.TWILIO_SEND_WHATSAPP]: Phone,
  [NodeType.TELEGRAM_SEND_MESSAGE]: Send,
  [NodeType.SLACK_MESSAGE_RECEIVED]: MessageSquare,
  [NodeType.SLACK_REACTION_ADDED]: Smile,
  [NodeType.DISCORD_MESSAGE_RECEIVED]: MessageSquare,
  [NodeType.TELEGRAM_MESSAGE_RECEIVED]: Send,
  [NodeType.TWILIO_SMS_RECEIVED]: Phone,
  [NodeType.NOTION_CREATE_PAGE]: BookText,
  [NodeType.NOTION_QUERY_DATABASE]: Search,
  [NodeType.TRELLO_CREATE_CARD]: CheckSquare,
  [NodeType.TRELLO_MOVE_CARD]: Move,
  [NodeType.AIRTABLE_CREATE_RECORD]: Database,
  [NodeType.AIRTABLE_UPDATE_RECORD]: Database,
  [NodeType.AIRTABLE_LIST_RECORDS]: Database,
  [NodeType.LINEAR_CREATE_ISSUE]: CircleDot,
  [NodeType.LINEAR_UPDATE_ISSUE_STATUS]: Tag,
  [NodeType.GITHUB_CREATE_ISSUE]: Github,
  [NodeType.GITHUB_COMMENT_ISSUE]: GitMerge,
  [NodeType.GITHUB_CREATE_PR]: GitPullRequest,
  [NodeType.CLAUDE_MESSAGES]: Sparkles,
  [NodeType.OPENAI_CHAT_COMPLETION]: Bot,
  [NodeType.OLLAMA_GENERATE]: Cpu,
  [NodeType.HUBSPOT_CREATE_CONTACT]: UserPlus,
  [NodeType.HUBSPOT_CREATE_DEAL]: Target,
  [NodeType.HUBSPOT_CONTACT_CHANGED]: Users,
  [NodeType.STRIPE_CREATE_CUSTOMER]: CreditCard,
  [NodeType.STRIPE_LIST_CHARGES]: CreditCard,
  [NodeType.STRIPE_EVENT_RECEIVED]: CreditCard,
  [NodeType.MAILCHIMP_ADD_SUBSCRIBER]: Mail,
  [NodeType.MAILCHIMP_SEND_CAMPAIGN]: Megaphone,
  [NodeType.MAILCHIMP_SUBSCRIBER_ADDED]: UserPlus,
  [NodeType.CALENDLY_LIST_EVENTS]: Calendar,
  [NodeType.CALENDLY_EVENT_SCHEDULED]: CalendarClock,
  [NodeType.POSTGRES_RUN_QUERY]: Database,
  [NodeType.MYSQL_RUN_QUERY]: Database,
  [NodeType.S3_UPLOAD_FILE]: CloudUpload,
  [NodeType.TRELLO_ADD_COMMENT]: MessageSquare,
  [NodeType.TRELLO_UPDATE_CARD]: Trello,
  [NodeType.TRELLO_CARD_CHANGED]: Trello,
};

export const DEFAULT_NODE_ICON: LucideIcon = Box;

export const getNodeIcon = (nodeType: NodeType | string): LucideIcon =>
  NODE_ICONS[nodeType as NodeType] ?? DEFAULT_NODE_ICON;
