export const NodeCategory = {
  TRIGGER: 'trigger',
  ACTION: 'action',
  LOGIC: 'logic',
  ANNOTATION: 'annotation',
} as const;

export type NodeCategory = (typeof NodeCategory)[keyof typeof NodeCategory];

export const NodeType = {
  MANUAL_TRIGGER: 'manual-trigger',
  CRON_TRIGGER: 'cron-trigger',
  WEBHOOK_TRIGGER: 'webhook-trigger',
  HTTP_REQUEST: 'http-request',
  CODE: 'code',
  CONDITIONAL: 'conditional',
  ITERATOR: 'iterator',
  SUBWORKFLOW: 'subworkflow',
  RETURN: 'return',
  STICKY: 'sticky',
  GMAIL_SEND: 'gmail-send',
  GMAIL_SEARCH: 'gmail-search',
  GMAIL_GET_MESSAGE: 'gmail-get-message',
  GMAIL_GET_ATTACHMENT: 'gmail-get-attachment',
  GMAIL_MODIFY_LABELS: 'gmail-modify-labels',
  GMAIL_CREATE_DRAFT: 'gmail-create-draft',
  DRIVE_CREATE: 'drive-create',
  DRIVE_LIST: 'drive-list',
  DRIVE_GET_FILE: 'drive-get-file',
  SHEETS_APPEND: 'sheets-append',
  SHEETS_READ: 'sheets-read',
  SHEETS_FIND_ROW: 'sheets-find-row',
  SHEETS_UPDATE_ROW: 'sheets-update-row',
  SHEETS_CLEAR_RANGE: 'sheets-clear-range',
  DOCS_CREATE: 'docs-create',
  DOCS_GET: 'docs-get',
  DOCS_INSERT_TEXT: 'docs-insert-text',
  DOCS_REPLACE_TEXT: 'docs-replace-text',
  CALENDAR_CREATE: 'calendar-create',
  CALENDAR_LIST_EVENTS: 'calendar-list-events',
  CALENDAR_GET_EVENT: 'calendar-get-event',
  GMAIL_MESSAGE_RECEIVED: 'gmail-message-received',
  GMAIL_LABEL_ADDED: 'gmail-label-added',
  GMAIL_ATTACHMENT_RECEIVED: 'gmail-attachment-received',
  DRIVE_FILE_ADDED: 'drive-file-added',
  DRIVE_FILE_UPDATED: 'drive-file-updated',
  SHEETS_ROW_ADDED: 'sheets-row-added',
  CALENDAR_EVENT_CREATED: 'calendar-event-created',
  CALENDAR_EVENT_UPDATED: 'calendar-event-updated',
  OUTLOOK_SEND: 'outlook-send',
  OUTLOOK_SEARCH: 'outlook-search',
  EXCEL_APPEND: 'excel-append',
  EXCEL_READ: 'excel-read',
  EXCEL_FIND_ROW: 'excel-find-row',
  EXCEL_UPDATE_ROW: 'excel-update-row',
  ONEDRIVE_CREATE: 'onedrive-create',
  ONEDRIVE_GET_FILE: 'onedrive-get-file',
  ONEDRIVE_LIST_FILES: 'onedrive-list-files',
  OUTLOOK_GET_MESSAGE: 'outlook-get-message',
  OUTLOOK_GET_ATTACHMENT: 'outlook-get-attachment',
  OUTLOOK_UPDATE_MESSAGE: 'outlook-update-message',
  OUTLOOK_CREATE_DRAFT: 'outlook-create-draft',
  OUTLOOK_MESSAGE_RECEIVED: 'outlook-message-received',
  OUTLOOK_MESSAGE_FLAGGED: 'outlook-message-flagged',
  ONEDRIVE_FILE_ADDED: 'onedrive-file-added',
  EXCEL_ROW_ADDED: 'excel-row-added',
  EXCEL_ROW_UPDATED: 'excel-row-updated',
  OUTLOOK_MESSAGE_WITH_ATTACHMENT: 'outlook-message-with-attachment',
  SLACK_POST_MESSAGE: 'slack-post-message',
  SLACK_POST_TO_CHANNEL: 'slack-post-to-channel',
  SLACK_UPLOAD_FILE: 'slack-upload-file',
  SLACK_FIND_USER: 'slack-find-user',
  SLACK_SEARCH_MESSAGES: 'slack-search-messages',
  SLACK_ADD_REACTION: 'slack-add-reaction',
  SLACK_CREATE_CHANNEL: 'slack-create-channel',
  SLACK_INVITE_TO_CHANNEL: 'slack-invite-to-channel',
  SLACK_GET_CHANNEL_HISTORY: 'slack-get-channel-history',
  SLACK_UPDATE_MESSAGE: 'slack-update-message',
  DISCORD_POST_WEBHOOK: 'discord-post-webhook',
  DISCORD_REPLY_TO_COMMAND: 'discord-reply-to-command',
  DISCORD_BOT_SEND_MESSAGE: 'discord-bot-send-message',
  DISCORD_GET_CHANNEL_MESSAGES: 'discord-get-channel-messages',
  DISCORD_ADD_ROLE: 'discord-add-role',
  TWILIO_SEND_SMS: 'twilio-send-sms',
  TWILIO_SEND_WHATSAPP: 'twilio-send-whatsapp',
  TWILIO_GET_MESSAGE: 'twilio-get-message',
  TWILIO_LIST_MESSAGES: 'twilio-list-messages',
  TWILIO_MAKE_CALL: 'twilio-make-call',
  TELEGRAM_SEND_MESSAGE: 'telegram-send-message',
  TELEGRAM_SEND_PHOTO: 'telegram-send-photo',
  TELEGRAM_SEND_DOCUMENT: 'telegram-send-document',
  TELEGRAM_EDIT_MESSAGE: 'telegram-edit-message',
  TELEGRAM_GET_CHAT: 'telegram-get-chat',
  SLACK_MESSAGE_RECEIVED: 'slack-message-received',
  SLACK_REACTION_ADDED: 'slack-reaction-added',
  SLACK_APP_MENTION: 'slack-app-mention',
  SLACK_CHANNEL_CREATED: 'slack-channel-created',
  DISCORD_MESSAGE_RECEIVED: 'discord-message-received',
  TELEGRAM_MESSAGE_RECEIVED: 'telegram-message-received',
  TELEGRAM_CALLBACK_QUERY_RECEIVED: 'telegram-callback-query-received',
  TWILIO_SMS_RECEIVED: 'twilio-sms-received',
  NOTION_CREATE_PAGE: 'notion-create-page',
  NOTION_QUERY_DATABASE: 'notion-query-database',
  TRELLO_CREATE_CARD: 'trello-create-card',
  TRELLO_MOVE_CARD: 'trello-move-card',
  AIRTABLE_CREATE_RECORD: 'airtable-create-record',
  AIRTABLE_UPDATE_RECORD: 'airtable-update-record',
  AIRTABLE_LIST_RECORDS: 'airtable-list-records',
  LINEAR_CREATE_ISSUE: 'linear-create-issue',
  LINEAR_UPDATE_ISSUE_STATUS: 'linear-update-issue-status',
  GITHUB_CREATE_ISSUE: 'github-create-issue',
  GITHUB_COMMENT_ISSUE: 'github-comment-issue',
  GITHUB_CREATE_PR: 'github-create-pr',
  CLAUDE_MESSAGES: 'claude-messages',
  OPENAI_CHAT_COMPLETION: 'openai-chat-completion',
  OLLAMA_GENERATE: 'ollama-generate',
  HUBSPOT_CREATE_CONTACT: 'hubspot-create-contact',
  HUBSPOT_CREATE_DEAL: 'hubspot-create-deal',
  STRIPE_CREATE_CUSTOMER: 'stripe-create-customer',
  STRIPE_LIST_CHARGES: 'stripe-list-charges',
  MAILCHIMP_ADD_SUBSCRIBER: 'mailchimp-add-subscriber',
  MAILCHIMP_SEND_CAMPAIGN: 'mailchimp-send-campaign',
  CALENDLY_LIST_EVENTS: 'calendly-list-events',
  POSTGRES_RUN_QUERY: 'postgres-run-query',
  MYSQL_RUN_QUERY: 'mysql-run-query',
  S3_UPLOAD_FILE: 's3-upload-file',
  TRELLO_ADD_COMMENT: 'trello-add-comment',
  TRELLO_UPDATE_CARD: 'trello-update-card',
  STRIPE_EVENT_RECEIVED: 'stripe-event-received',
  HUBSPOT_CONTACT_CHANGED: 'hubspot-contact-changed',
  MAILCHIMP_SUBSCRIBER_ADDED: 'mailchimp-subscriber-added',
  CALENDLY_EVENT_SCHEDULED: 'calendly-event-scheduled',
  TRELLO_CARD_CHANGED: 'trello-card-changed',
  // S15 — productivity & dev-tools read/update pack (#244)
  NOTION_GET_PAGE: 'notion-get-page',
  NOTION_UPDATE_PAGE: 'notion-update-page',
  NOTION_APPEND_BLOCKS: 'notion-append-blocks',
  NOTION_GET_BLOCK_CHILDREN: 'notion-get-block-children',
  NOTION_FIND_DATABASE_ITEM: 'notion-find-database-item',
  TRELLO_GET_CARD: 'trello-get-card',
  TRELLO_LIST_CARDS: 'trello-list-cards',
  TRELLO_CREATE_LIST: 'trello-create-list',
  AIRTABLE_GET_RECORD: 'airtable-get-record',
  AIRTABLE_FIND_RECORDS: 'airtable-find-records',
  AIRTABLE_DELETE_RECORD: 'airtable-delete-record',
  LINEAR_GET_ISSUE: 'linear-get-issue',
  LINEAR_SEARCH_ISSUES: 'linear-search-issues',
  LINEAR_ADD_COMMENT: 'linear-add-comment',
  GITHUB_GET_ISSUE: 'github-get-issue',
  GITHUB_LIST_ISSUES: 'github-list-issues',
  GITHUB_CLOSE_ISSUE: 'github-close-issue',
  GITHUB_GET_REPO: 'github-get-repo',
  GITHUB_LIST_PRS: 'github-list-prs',
  GITHUB_MERGE_PR: 'github-merge-pr',
  NOTION_DATABASE_ITEM_UPDATED: 'notion-database-item-updated',
  AIRTABLE_RECORD_CREATED: 'airtable-record-created',
  LINEAR_ISSUE_UPDATED: 'linear-issue-updated',
  GITHUB_ISSUE_OPENED: 'github-issue-opened',
  GITHUB_PR_OPENED: 'github-pr-opened',
  // S15 — commerce, data & storage read/update pack (#246)
  STRIPE_GET_CUSTOMER: 'stripe-get-customer',
  STRIPE_FIND_CUSTOMER: 'stripe-find-customer',
  STRIPE_CREATE_PAYMENT_INTENT: 'stripe-create-payment-intent',
  STRIPE_CREATE_REFUND: 'stripe-create-refund',
  STRIPE_LIST_INVOICES: 'stripe-list-invoices',
  STRIPE_CREATE_SUBSCRIPTION: 'stripe-create-subscription',
  HUBSPOT_FIND_CONTACT: 'hubspot-find-contact',
  HUBSPOT_GET_CONTACT: 'hubspot-get-contact',
  HUBSPOT_UPDATE_CONTACT: 'hubspot-update-contact',
  HUBSPOT_UPDATE_DEAL: 'hubspot-update-deal',
  HUBSPOT_CREATE_COMPANY: 'hubspot-create-company',
  HUBSPOT_CREATE_NOTE: 'hubspot-create-note',
  MAILCHIMP_GET_SUBSCRIBER: 'mailchimp-get-subscriber',
  MAILCHIMP_UPDATE_SUBSCRIBER: 'mailchimp-update-subscriber',
  MAILCHIMP_UNSUBSCRIBE: 'mailchimp-unsubscribe',
  MAILCHIMP_ADD_TAG: 'mailchimp-add-tag',
  MAILCHIMP_LIST_CAMPAIGNS: 'mailchimp-list-campaigns',
  CALENDLY_GET_EVENT: 'calendly-get-event',
  CALENDLY_CANCEL_EVENT: 'calendly-cancel-event',
  CALENDLY_LIST_INVITEES: 'calendly-list-invitees',
  S3_DOWNLOAD_FILE: 's3-download-file',
  S3_LIST_OBJECTS: 's3-list-objects',
  S3_DELETE_OBJECT: 's3-delete-object',
  S3_GET_PRESIGNED_URL: 's3-get-presigned-url',
  OPENAI_EMBEDDINGS: 'openai-embeddings',
  OPENAI_GENERATE_IMAGE: 'openai-generate-image',
  ANTHROPIC_VISION: 'anthropic-vision',
  OLLAMA_EMBEDDINGS: 'ollama-embeddings',
  AI_GENERATE_IMAGE: 'ai-generate-image',
  INSTAGRAM_PUBLISH_PHOTO: 'instagram-publish-photo',
  INSTAGRAM_COMMENT_ADDED: 'instagram-comment-added',
  WHATSAPP_SEND_MESSAGE: 'whatsapp-send-message',
  WHATSAPP_SEND_TEMPLATE: 'whatsapp-send-template',
  WHATSAPP_MESSAGE_RECEIVED: 'whatsapp-message-received',
  STRIPE_INVOICE_PAID: 'stripe-invoice-paid',
  HUBSPOT_DEAL_CHANGED: 'hubspot-deal-changed',
  S3_OBJECT_CREATED: 's3-object-created',
} as const;

export type NodeType = (typeof NodeType)[keyof typeof NodeType];

export const NodeGroup = {
  TRIGGERS: 'triggers',
  GOOGLE_TRIGGERS: 'google-triggers',
  MICROSOFT_TRIGGERS: 'microsoft-triggers',
  COMMUNICATION_TRIGGERS: 'communication-triggers',
  COMMERCE_TRIGGERS: 'commerce-triggers',
  PRODUCTIVITY_TRIGGERS: 'productivity-triggers',
  ACTIONS: 'actions',
  LOGIC: 'logic',
  DATA: 'data',
  AI: 'ai',
  COMMUNICATION: 'communication',
  PRODUCTIVITY: 'productivity',
  COMMERCE: 'commerce',
  CUSTOM: 'custom',
} as const;

export type NodeGroup = (typeof NodeGroup)[keyof typeof NodeGroup];

// Stable display order for the SPA's node-library palette.
export const NODE_GROUP_ORDER: readonly NodeGroup[] = [
  NodeGroup.TRIGGERS,
  NodeGroup.GOOGLE_TRIGGERS,
  NodeGroup.MICROSOFT_TRIGGERS,
  NodeGroup.COMMUNICATION_TRIGGERS,
  NodeGroup.COMMERCE_TRIGGERS,
  NodeGroup.PRODUCTIVITY_TRIGGERS,
  NodeGroup.ACTIONS,
  NodeGroup.LOGIC,
  NodeGroup.DATA,
  NodeGroup.AI,
  NodeGroup.COMMUNICATION,
  NodeGroup.PRODUCTIVITY,
  NodeGroup.COMMERCE,
  NodeGroup.CUSTOM,
];

export const NODE_GROUP_LABELS: Record<NodeGroup, string> = {
  [NodeGroup.TRIGGERS]: 'Triggers',
  [NodeGroup.GOOGLE_TRIGGERS]: 'Google Triggers',
  [NodeGroup.MICROSOFT_TRIGGERS]: 'Microsoft Triggers',
  [NodeGroup.COMMUNICATION_TRIGGERS]: 'Communication Triggers',
  [NodeGroup.COMMERCE_TRIGGERS]: 'Commerce Triggers',
  [NodeGroup.PRODUCTIVITY_TRIGGERS]: 'Productivity Triggers',
  [NodeGroup.ACTIONS]: 'Actions',
  [NodeGroup.LOGIC]: 'Logic',
  [NodeGroup.DATA]: 'Data',
  [NodeGroup.AI]: 'AI',
  [NodeGroup.COMMUNICATION]: 'Communication',
  [NodeGroup.PRODUCTIVITY]: 'Productivity',
  [NodeGroup.COMMERCE]: 'Commerce',
  [NodeGroup.CUSTOM]: 'Custom',
};

export interface NodeTypeDefinition {
  type: NodeType;
  name: string;
  description: string;
  category: NodeCategory;
  // Optional palette-display group. When omitted, the SPA infers from `category`
  // (trigger → triggers, action → actions, logic → logic). Domain-specific groups
  // (data/ai/communication/...) are reserved for future connector nodes.
  group?: NodeGroup;
  // Optional provider tag used for palette filtering (e.g. 'slack', 'openai').
  provider?: string;
}
