export const NodeCategory = {
  TRIGGER: 'trigger',
  ACTION: 'action',
  LOGIC: 'logic',
  ANNOTATION: 'annotation',
} as const;

export type NodeCategory = (typeof NodeCategory)[keyof typeof NodeCategory];

export const NodeType = {
  MANUAL_TRIGGER: 'manual-trigger',
  CRON_TRIGGER: 'cron-trigger',
  WEBHOOK_TRIGGER: 'webhook-trigger',
  HTTP_REQUEST: 'http-request',
  CODE: 'code',
  CONDITIONAL: 'conditional',
  ITERATOR: 'iterator',
  SUBWORKFLOW: 'subworkflow',
  RETURN: 'return',
  STICKY: 'sticky',
  GMAIL_SEND: 'gmail-send',
  GMAIL_SEARCH: 'gmail-search',
  GMAIL_GET_MESSAGE: 'gmail-get-message',
  GMAIL_GET_ATTACHMENT: 'gmail-get-attachment',
  GMAIL_MODIFY_LABELS: 'gmail-modify-labels',
  GMAIL_CREATE_DRAFT: 'gmail-create-draft',
  DRIVE_CREATE: 'drive-create',
  DRIVE_LIST: 'drive-list',
  DRIVE_GET_FILE: 'drive-get-file',
  SHEETS_APPEND: 'sheets-append',
  SHEETS_READ: 'sheets-read',
  SHEETS_FIND_ROW: 'sheets-find-row',
  SHEETS_UPDATE_ROW: 'sheets-update-row',
  SHEETS_CLEAR_RANGE: 'sheets-clear-range',
  DOCS_CREATE: 'docs-create',
  DOCS_GET: 'docs-get',
  DOCS_INSERT_TEXT: 'docs-insert-text',
  DOCS_REPLACE_TEXT: 'docs-replace-text',
  CALENDAR_CREATE: 'calendar-create',
  CALENDAR_LIST_EVENTS: 'calendar-list-events',
  CALENDAR_GET_EVENT: 'calendar-get-event',
  GMAIL_MESSAGE_RECEIVED: 'gmail-message-received',
  GMAIL_LABEL_ADDED: 'gmail-label-added',
  GMAIL_ATTACHMENT_RECEIVED: 'gmail-attachment-received',
  DRIVE_FILE_ADDED: 'drive-file-added',
  DRIVE_FILE_UPDATED: 'drive-file-updated',
  SHEETS_ROW_ADDED: 'sheets-row-added',
  CALENDAR_EVENT_CREATED: 'calendar-event-created',
  CALENDAR_EVENT_UPDATED: 'calendar-event-updated',
  OUTLOOK_SEND: 'outlook-send',
  OUTLOOK_SEARCH: 'outlook-search',
  EXCEL_APPEND: 'excel-append',
  EXCEL_READ: 'excel-read',
  EXCEL_FIND_ROW: 'excel-find-row',
  EXCEL_UPDATE_ROW: 'excel-update-row',
  ONEDRIVE_CREATE: 'onedrive-create',
  ONEDRIVE_GET_FILE: 'onedrive-get-file',
  ONEDRIVE_LIST_FILES: 'onedrive-list-files',
  OUTLOOK_GET_MESSAGE: 'outlook-get-message',
  OUTLOOK_GET_ATTACHMENT: 'outlook-get-attachment',
  OUTLOOK_UPDATE_MESSAGE: 'outlook-update-message',
  OUTLOOK_CREATE_DRAFT: 'outlook-create-draft',
  OUTLOOK_MESSAGE_RECEIVED: 'outlook-message-received',
  OUTLOOK_MESSAGE_FLAGGED: 'outlook-message-flagged',
  ONEDRIVE_FILE_ADDED: 'onedrive-file-added',
  EXCEL_ROW_ADDED: 'excel-row-added',
  EXCEL_ROW_UPDATED: 'excel-row-updated',
  OUTLOOK_MESSAGE_WITH_ATTACHMENT: 'outlook-message-with-attachment',
  SLACK_POST_MESSAGE: 'slack-post-message',
  SLACK_POST_TO_CHANNEL: 'slack-post-to-channel',
  SLACK_UPLOAD_FILE: 'slack-upload-file',
  SLACK_FIND_USER: 'slack-find-user',
  SLACK_SEARCH_MESSAGES: 'slack-search-messages',
  SLACK_ADD_REACTION: 'slack-add-reaction',
  SLACK_CREATE_CHANNEL: 'slack-create-channel',
  SLACK_INVITE_TO_CHANNEL: 'slack-invite-to-channel',
  SLACK_GET_CHANNEL_HISTORY: 'slack-get-channel-history',
  SLACK_UPDATE_MESSAGE: 'slack-update-message',
  DISCORD_POST_WEBHOOK: 'discord-post-webhook',
  DISCORD_REPLY_TO_COMMAND: 'discord-reply-to-command',
  DISCORD_BOT_SEND_MESSAGE: 'discord-bot-send-message',
  DISCORD_GET_CHANNEL_MESSAGES: 'discord-get-channel-messages',
  DISCORD_ADD_ROLE: 'discord-add-role',
  TWILIO_SEND_SMS: 'twilio-send-sms',
  TWILIO_SEND_WHATSAPP: 'twilio-send-whatsapp',
  TELEGRAM_SEND_MESSAGE: 'telegram-send-message',
  SLACK_MESSAGE_RECEIVED: 'slack-message-received',
  SLACK_REACTION_ADDED: 'slack-reaction-added',
  DISCORD_MESSAGE_RECEIVED: 'discord-message-received',
  TELEGRAM_MESSAGE_RECEIVED: 'telegram-message-received',
  TWILIO_SMS_RECEIVED: 'twilio-sms-received',
  NOTION_CREATE_PAGE: 'notion-create-page',
  NOTION_QUERY_DATABASE: 'notion-query-database',
  TRELLO_CREATE_CARD: 'trello-create-card',
  TRELLO_MOVE_CARD: 'trello-move-card',
  AIRTABLE_CREATE_RECORD: 'airtable-create-record',
  AIRTABLE_UPDATE_RECORD: 'airtable-update-record',
  AIRTABLE_LIST_RECORDS: 'airtable-list-records',
  LINEAR_CREATE_ISSUE: 'linear-create-issue',
  LINEAR_UPDATE_ISSUE_STATUS: 'linear-update-issue-status',
  GITHUB_CREATE_ISSUE: 'github-create-issue',
  GITHUB_COMMENT_ISSUE: 'github-comment-issue',
  GITHUB_CREATE_PR: 'github-create-pr',
  CLAUDE_MESSAGES: 'claude-messages',
  OPENAI_CHAT_COMPLETION: 'openai-chat-completion',
  OLLAMA_GENERATE: 'ollama-generate',
  HUBSPOT_CREATE_CONTACT: 'hubspot-create-contact',
  HUBSPOT_CREATE_DEAL: 'hubspot-create-deal',
  STRIPE_CREATE_CUSTOMER: 'stripe-create-customer',
  STRIPE_LIST_CHARGES: 'stripe-list-charges',
  MAILCHIMP_ADD_SUBSCRIBER: 'mailchimp-add-subscriber',
  MAILCHIMP_SEND_CAMPAIGN: 'mailchimp-send-campaign',
  CALENDLY_LIST_EVENTS: 'calendly-list-events',
  POSTGRES_RUN_QUERY: 'postgres-run-query',
  MYSQL_RUN_QUERY: 'mysql-run-query',
  S3_UPLOAD_FILE: 's3-upload-file',
  TRELLO_ADD_COMMENT: 'trello-add-comment',
  TRELLO_UPDATE_CARD: 'trello-update-card',
  STRIPE_EVENT_RECEIVED: 'stripe-event-received',
  HUBSPOT_CONTACT_CHANGED: 'hubspot-contact-changed',
  MAILCHIMP_SUBSCRIBER_ADDED: 'mailchimp-subscriber-added',
  CALENDLY_EVENT_SCHEDULED: 'calendly-event-scheduled',
  TRELLO_CARD_CHANGED: 'trello-card-changed',
  // S15 — productivity & dev-tools read/update pack (#244)
  NOTION_GET_PAGE: 'notion-get-page',
  NOTION_UPDATE_PAGE: 'notion-update-page',
  NOTION_APPEND_BLOCKS: 'notion-append-blocks',
  NOTION_GET_BLOCK_CHILDREN: 'notion-get-block-children',
  NOTION_FIND_DATABASE_ITEM: 'notion-find-database-item',
  TRELLO_GET_CARD: 'trello-get-card',
  TRELLO_LIST_CARDS: 'trello-list-cards',
  TRELLO_CREATE_LIST: 'trello-create-list',
  AIRTABLE_GET_RECORD: 'airtable-get-record',
  AIRTABLE_FIND_RECORDS: 'airtable-find-records',
  AIRTABLE_DELETE_RECORD: 'airtable-delete-record',
  LINEAR_GET_ISSUE: 'linear-get-issue',
  LINEAR_SEARCH_ISSUES: 'linear-search-issues',
  LINEAR_ADD_COMMENT: 'linear-add-comment',
  GITHUB_GET_ISSUE: 'github-get-issue',
  GITHUB_LIST_ISSUES: 'github-list-issues',
  GITHUB_CLOSE_ISSUE: 'github-close-issue',
  GITHUB_GET_REPO: 'github-get-repo',
  GITHUB_LIST_PRS: 'github-list-prs',
  GITHUB_MERGE_PR: 'github-merge-pr',
  NOTION_DATABASE_ITEM_UPDATED: 'notion-database-item-updated',
  AIRTABLE_RECORD_CREATED: 'airtable-record-created',
  LINEAR_ISSUE_UPDATED: 'linear-issue-updated',
  GITHUB_ISSUE_OPENED: 'github-issue-opened',
  GITHUB_PR_OPENED: 'github-pr-opened',
} as const;

export type NodeType = (typeof NodeType)[keyof typeof NodeType];

export const NodeGroup = {
  TRIGGERS: 'triggers',
  GOOGLE_TRIGGERS: 'google-triggers',
  MICROSOFT_TRIGGERS: 'microsoft-triggers',
  COMMUNICATION_TRIGGERS: 'communication-triggers',
  COMMERCE_TRIGGERS: 'commerce-triggers',
  PRODUCTIVITY_TRIGGERS: 'productivity-triggers',
  ACTIONS: 'actions',
  LOGIC: 'logic',
  DATA: 'data',
  AI: 'ai',
  COMMUNICATION: 'communication',
  PRODUCTIVITY: 'productivity',
  COMMERCE: 'commerce',
  CUSTOM: 'custom',
} as const;

export type NodeGroup = (typeof NodeGroup)[keyof typeof NodeGroup];

// Stable display order for the SPA's node-library palette.
export const NODE_GROUP_ORDER: readonly NodeGroup[] = [
  NodeGroup.TRIGGERS,
  NodeGroup.GOOGLE_TRIGGERS,
  NodeGroup.MICROSOFT_TRIGGERS,
  NodeGroup.COMMUNICATION_TRIGGERS,
  NodeGroup.COMMERCE_TRIGGERS,
  NodeGroup.PRODUCTIVITY_TRIGGERS,
  NodeGroup.ACTIONS,
  NodeGroup.LOGIC,
  NodeGroup.DATA,
  NodeGroup.AI,
  NodeGroup.COMMUNICATION,
  NodeGroup.PRODUCTIVITY,
  NodeGroup.COMMERCE,
  NodeGroup.CUSTOM,
];

export const NODE_GROUP_LABELS: Record<NodeGroup, string> = {
  [NodeGroup.TRIGGERS]: 'Triggers',
  [NodeGroup.GOOGLE_TRIGGERS]: 'Google Triggers',
  [NodeGroup.MICROSOFT_TRIGGERS]: 'Microsoft Triggers',
  [NodeGroup.COMMUNICATION_TRIGGERS]: 'Communication Triggers',
  [NodeGroup.COMMERCE_TRIGGERS]: 'Commerce Triggers',
  [NodeGroup.PRODUCTIVITY_TRIGGERS]: 'Productivity Triggers',
  [NodeGroup.ACTIONS]: 'Actions',
  [NodeGroup.LOGIC]: 'Logic',
  [NodeGroup.DATA]: 'Data',
  [NodeGroup.AI]: 'AI',
  [NodeGroup.COMMUNICATION]: 'Communication',
  [NodeGroup.PRODUCTIVITY]: 'Productivity',
  [NodeGroup.COMMERCE]: 'Commerce',
  [NodeGroup.CUSTOM]: 'Custom',
};

export interface NodeTypeDefinition {
  type: NodeType;
  name: string;
  description: string;
  category: NodeCategory;
  // Optional palette-display group. When omitted, the SPA infers from `category`
  // (trigger → triggers, action → actions, logic → logic). Domain-specific groups
  // (data/ai/communication/...) are reserved for future connector nodes.
  group?: NodeGroup;
  // Optional provider tag used for palette filtering (e.g. 'slack', 'openai').
  provider?: string;
}

export const NODE_CATALOG: NodeTypeDefinition[] = [
  {
    type: NodeType.MANUAL_TRIGGER,
    name: 'Manual Trigger',
    description: 'Start workflow manually',
    category: NodeCategory.TRIGGER,
  },
  {
    type: NodeType.CRON_TRIGGER,
    name: 'Cron Trigger',
    description: 'Start workflow on a schedule',
    category: NodeCategory.TRIGGER,
  },
  {
    type: NodeType.WEBHOOK_TRIGGER,
    name: 'Webhook Trigger',
    description: 'Start workflow via HTTP webhook',
    category: NodeCategory.TRIGGER,
  },
  {
    type: NodeType.HTTP_REQUEST,
    name: 'HTTP Request',
    description: 'Make an HTTP request to an external API',
    category: NodeCategory.ACTION,
  },
  {
    type: NodeType.CODE,
    name: 'Code',
    description: 'Execute custom JavaScript code',
    category: NodeCategory.ACTION,
  },
  {
    type: NodeType.CONDITIONAL,
    name: 'Conditional (IF)',
    description: 'Branch based on a condition',
    category: NodeCategory.LOGIC,
  },
  {
    type: NodeType.ITERATOR,
    name: 'Iterator (For Each)',
    description: 'Run downstream subgraph once per item in an array',
    category: NodeCategory.LOGIC,
  },
  {
    type: NodeType.SUBWORKFLOW,
    name: 'Subworkflow',
    description: 'Invoke another workflow synchronously and use its return value',
    category: NodeCategory.LOGIC,
  },
  {
    type: NodeType.RETURN,
    name: 'Return',
    description: 'Mark the value to forward to a parent subworkflow caller',
    category: NodeCategory.LOGIC,
  },
  {
    type: NodeType.STICKY,
    name: 'Sticky Note',
    description: 'Add a colored note for documentation. Does not execute.',
    category: NodeCategory.ANNOTATION,
    group: NodeGroup.CUSTOM,
  },
  {
    type: NodeType.GMAIL_SEND,
    name: 'Gmail: Send Email',
    description: 'Send an email via Gmail',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_SEARCH,
    name: 'Gmail: Search Messages',
    description: 'Search Gmail messages with Gmail search syntax',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_GET_MESSAGE,
    name: 'Gmail: Get Message',
    description: 'Fetch a Gmail message by ID (headers, decoded body, attachment list)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_GET_ATTACHMENT,
    name: 'Gmail: Get Attachment',
    description: 'Download a Gmail attachment by message ID and attachment ID (base64)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_MODIFY_LABELS,
    name: 'Gmail: Modify Labels',
    description: 'Add/remove labels, archive, or mark a Gmail message read/unread',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_CREATE_DRAFT,
    name: 'Gmail: Create Draft',
    description: 'Create a Gmail draft (optionally a reply within a thread)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.DRIVE_CREATE,
    name: 'Drive: Create File',
    description: 'Create a file in Google Drive',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DRIVE_LIST,
    name: 'Drive: List Files',
    description: 'List files in a Google Drive folder',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DRIVE_GET_FILE,
    name: 'Drive: Get File',
    description: 'Fetch Drive file metadata, with optional content download (base64)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_APPEND,
    name: 'Sheets: Append Row',
    description: 'Append a row of values to a Google Sheet',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_READ,
    name: 'Sheets: Read Range',
    description: 'Read a range from a Google Sheet (A1 notation)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_FIND_ROW,
    name: 'Sheets: Find Row',
    description: 'Find rows in a Google Sheet where a column equals a value',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_UPDATE_ROW,
    name: 'Sheets: Update Row',
    description: 'Overwrite a row in a Google Sheet by its row number',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_CLEAR_RANGE,
    name: 'Sheets: Clear Range',
    description: 'Clear all values in a range of a Google Sheet (A1 notation)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DOCS_CREATE,
    name: 'Docs: Create From Template',
    description: 'Copy a Google Doc template and replace placeholders',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DOCS_GET,
    name: 'Docs: Get Document',
    description: 'Read a Google Doc — title, plain text, and structural content',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DOCS_INSERT_TEXT,
    name: 'Docs: Insert Text',
    description: 'Insert text at an index in a Google Doc, or append to the end',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DOCS_REPLACE_TEXT,
    name: 'Docs: Replace Text',
    description: 'Find and replace text tokens in a Google Doc (template fill)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.CALENDAR_CREATE,
    name: 'Calendar: Create Event',
    description: 'Create a Google Calendar event',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.CALENDAR_LIST_EVENTS,
    name: 'Calendar: List Events',
    description: 'List Google Calendar events in a time window',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.CALENDAR_GET_EVENT,
    name: 'Calendar: Get Event',
    description: 'Fetch a single Google Calendar event by ID',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.OUTLOOK_SEND,
    name: 'Outlook: Send Email',
    description: 'Send an email via Outlook (Microsoft 365)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_SEARCH,
    name: 'Outlook: Search Inbox',
    description: 'Search Outlook messages with Microsoft Search syntax',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_GET_MESSAGE,
    name: 'Outlook: Get Message',
    description: 'Fetch a full Outlook message by ID (headers, body, attachment list)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_GET_ATTACHMENT,
    name: 'Outlook: Get Attachment',
    description: 'Download an Outlook attachment by message + attachment ID (base64)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_UPDATE_MESSAGE,
    name: 'Outlook: Update Message',
    description: 'Flag, categorize, mark read/unread, or move an Outlook message',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_CREATE_DRAFT,
    name: 'Outlook: Create Draft',
    description: 'Create a draft email, or a reply draft to an existing message',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_APPEND,
    name: 'Excel: Append Row',
    description: 'Append rows of values to an Excel Online worksheet',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_READ,
    name: 'Excel: Read Range',
    description: 'Read a range from an Excel Online worksheet (A1 notation)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_FIND_ROW,
    name: 'Excel: Find Row',
    description: 'Find table rows where a column matches a value (exact/contains/startsWith)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_UPDATE_ROW,
    name: 'Excel: Update Row',
    description: 'Overwrite an Excel table row by index or by a unique column lookup',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.ONEDRIVE_CREATE,
    name: 'OneDrive: Create File',
    description: 'Create a file in OneDrive',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.ONEDRIVE_GET_FILE,
    name: 'OneDrive: Get File',
    description: 'Fetch OneDrive file metadata and optionally download its content',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.ONEDRIVE_LIST_FILES,
    name: 'OneDrive: List Files',
    description: 'List items in a OneDrive folder (by id, path, or the drive root)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.GMAIL_MESSAGE_RECEIVED,
    name: 'Gmail: Message Received',
    description:
      'Trigger when a new Gmail message arrives (poll by default; push via Cloud Pub/Sub when configured)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_LABEL_ADDED,
    name: 'Gmail: Label Added',
    description: 'Trigger when a label is added to a Gmail message (poll, historyId-based)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_ATTACHMENT_RECEIVED,
    name: 'Gmail: Attachment Received',
    description: 'Trigger when a new Gmail message arrives with an attachment (poll, historyId)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.DRIVE_FILE_ADDED,
    name: 'Drive: File Added',
    description: 'Trigger when a file is added to a Google Drive folder (push, watch channel)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.DRIVE_FILE_UPDATED,
    name: 'Drive: File Updated',
    description: 'Trigger when a watched Google Drive file is modified (push, watch channel)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_ROW_ADDED,
    name: 'Sheets: Row Added',
    description: 'Trigger when a new row is appended to a Google Sheet (poll, row-count cursor)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.CALENDAR_EVENT_CREATED,
    name: 'Calendar: Event Created',
    description: 'Trigger when a new event is created in a Google Calendar (poll, updatedMin)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.CALENDAR_EVENT_UPDATED,
    name: 'Calendar: Event Updated',
    description:
      'Trigger when a Google Calendar event is changed or cancelled (poll, updated watermark)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.OUTLOOK_MESSAGE_RECEIVED,
    name: 'Outlook: Message Received',
    description:
      'Trigger when a new email arrives in the Outlook inbox (push, MS Graph subscription)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_MESSAGE_FLAGGED,
    name: 'Outlook: Message Flagged',
    description: 'Trigger when an Outlook message is flagged for follow-up (push, MS Graph)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
  {
    type: NodeType.ONEDRIVE_FILE_ADDED,
    name: 'OneDrive: File Added',
    description: 'Trigger when a file is added to OneDrive (push, MS Graph drive subscription)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_ROW_ADDED,
    name: 'Excel: Row Added',
    description:
      'Trigger when a new row is added to an Excel Online table (poll, row-index cursor)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_ROW_UPDATED,
    name: 'Excel: Row Updated',
    description:
      'Trigger when an existing Excel Online table row changes (poll, per-row value hash)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_MESSAGE_WITH_ATTACHMENT,
    name: 'Outlook: Message With Attachment',
    description:
      'Trigger when a new Outlook inbox message with attachments arrives (push, MS Graph subscription)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
  {
    type: NodeType.SLACK_POST_MESSAGE,
    name: 'Slack: Post Message',
    description: 'Post a message to a Slack channel by ID (supports Block Kit blocks)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_POST_TO_CHANNEL,
    name: 'Slack: Post to Channel by Name',
    description: 'Look up a Slack channel by name and post a message',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_UPLOAD_FILE,
    name: 'Slack: Upload File',
    description: 'Upload a base64 file payload to a Slack channel',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_FIND_USER,
    name: 'Slack: Find User',
    description: 'Find a Slack user by email or by name',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_SEARCH_MESSAGES,
    name: 'Slack: Search Messages',
    description: 'Search Slack messages (requires a user token with search:read)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_ADD_REACTION,
    name: 'Slack: Add Reaction',
    description: 'Add an emoji reaction to a Slack message',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_CREATE_CHANNEL,
    name: 'Slack: Create Channel',
    description: 'Create a public or private Slack channel',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_INVITE_TO_CHANNEL,
    name: 'Slack: Invite to Channel',
    description: 'Invite one or more users to a Slack channel',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_GET_CHANNEL_HISTORY,
    name: 'Slack: Get Channel History',
    description: 'Read recent messages from a Slack channel',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_UPDATE_MESSAGE,
    name: 'Slack: Update Message',
    description: 'Edit a previously posted Slack message by timestamp',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.DISCORD_POST_WEBHOOK,
    name: 'Discord: Post via Webhook',
    description: 'Send a message to a Discord channel via its incoming webhook URL',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'discord',
  },
  {
    type: NodeType.DISCORD_REPLY_TO_COMMAND,
    name: 'Discord: Reply to Slash Command',
    description: 'Reply to the Discord slash command that triggered this workflow with a message',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'discord',
  },
  {
    type: NodeType.DISCORD_BOT_SEND_MESSAGE,
    name: 'Discord: Send Message (Bot)',
    description: 'Post a message to a Discord channel using a bot token (REST API)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'discord-bot',
  },
  {
    type: NodeType.DISCORD_GET_CHANNEL_MESSAGES,
    name: 'Discord: Get Channel Messages',
    description: 'Read recent messages from a Discord channel using a bot token',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'discord-bot',
  },
  {
    type: NodeType.DISCORD_ADD_ROLE,
    name: 'Discord: Add Role',
    description: 'Assign a role to a guild member using a bot token',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'discord-bot',
  },
  {
    type: NodeType.TWILIO_SEND_SMS,
    name: 'Twilio: Send SMS',
    description: 'Send an SMS via Twilio to an E.164 number',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'twilio',
  },
  {
    type: NodeType.TWILIO_SEND_WHATSAPP,
    name: 'Twilio: Send WhatsApp Template',
    description: 'Send a Twilio WhatsApp message using an approved Content template',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'twilio',
  },
  {
    type: NodeType.TELEGRAM_SEND_MESSAGE,
    name: 'Telegram: Send Message',
    description: 'Send a message via a Telegram bot to a chat or channel',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'telegram',
  },
  {
    type: NodeType.SLACK_MESSAGE_RECEIVED,
    name: 'Slack: Message Received',
    description: 'Trigger when a message is posted to a Slack channel (push, Slack Events API)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMUNICATION_TRIGGERS,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_REACTION_ADDED,
    name: 'Slack: Reaction Added',
    description: 'Trigger when a reaction is added to a Slack message (push, Slack Events API)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMUNICATION_TRIGGERS,
    provider: 'slack',
  },
  {
    type: NodeType.DISCORD_MESSAGE_RECEIVED,
    name: 'Discord: Slash Command Received',
    description:
      'Trigger on a Discord slash command invocation (push, Interactions endpoint, ed25519)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMUNICATION_TRIGGERS,
    provider: 'discord-bot',
  },
  {
    type: NodeType.TELEGRAM_MESSAGE_RECEIVED,
    name: 'Telegram: Message Received',
    description: 'Trigger when a Telegram bot receives a message (push, setWebhook + secret_token)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMUNICATION_TRIGGERS,
    provider: 'telegram',
  },
  {
    type: NodeType.TWILIO_SMS_RECEIVED,
    name: 'Twilio: SMS Received',
    description: 'Trigger when a Twilio phone number receives an SMS (push, X-Twilio-Signature)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMUNICATION_TRIGGERS,
    provider: 'twilio',
  },
  {
    type: NodeType.NOTION_CREATE_PAGE,
    name: 'Notion: Create Page',
    description: 'Create a new page under a parent page or database',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'notion',
  },
  {
    type: NodeType.NOTION_QUERY_DATABASE,
    name: 'Notion: Query Database',
    description: 'Query rows from a Notion database with filter/sort',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'notion',
  },
  {
    type: NodeType.TRELLO_CREATE_CARD,
    name: 'Trello: Create Card',
    description: 'Create a Trello card on a board list',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'trello',
  },
  {
    type: NodeType.TRELLO_MOVE_CARD,
    name: 'Trello: Move Card',
    description: 'Move an existing Trello card to a different list',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'trello',
  },
  {
    type: NodeType.AIRTABLE_CREATE_RECORD,
    name: 'Airtable: Create Record',
    description: 'Create a record in an Airtable table',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'airtable',
  },
  {
    type: NodeType.AIRTABLE_UPDATE_RECORD,
    name: 'Airtable: Update Record',
    description: 'Patch fields on an existing Airtable record',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'airtable',
  },
  {
    type: NodeType.AIRTABLE_LIST_RECORDS,
    name: 'Airtable: List Records',
    description: 'List records from an Airtable table with optional filterByFormula',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'airtable',
  },
  {
    type: NodeType.LINEAR_CREATE_ISSUE,
    name: 'Linear: Create Issue',
    description: 'Create a Linear issue in a team',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'linear',
  },
  {
    type: NodeType.LINEAR_UPDATE_ISSUE_STATUS,
    name: 'Linear: Update Issue Status',
    description: 'Move a Linear issue to a different workflow state',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'linear',
  },
  {
    type: NodeType.GITHUB_CREATE_ISSUE,
    name: 'GitHub: Create Issue',
    description: 'Open a new issue in a GitHub repository',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_COMMENT_ISSUE,
    name: 'GitHub: Comment on Issue',
    description: 'Post a comment on a GitHub issue or pull request',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_CREATE_PR,
    name: 'GitHub: Create Pull Request',
    description: 'Open a pull request from one branch into another',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.CLAUDE_MESSAGES,
    name: 'Claude: Messages',
    description: 'Send a prompt to the Anthropic Messages API and capture the response',
    category: NodeCategory.ACTION,
    group: NodeGroup.AI,
    provider: 'anthropic',
  },
  {
    type: NodeType.OPENAI_CHAT_COMPLETION,
    name: 'OpenAI: Chat Completion',
    description: 'Send a chat completion request to OpenAI (gpt-4o, gpt-4-turbo, etc.)',
    category: NodeCategory.ACTION,
    group: NodeGroup.AI,
    provider: 'openai',
  },
  {
    type: NodeType.OLLAMA_GENERATE,
    name: 'Ollama: Generate',
    description: 'Generate text from a self-hosted Ollama server (per-workspace connection)',
    category: NodeCategory.ACTION,
    group: NodeGroup.AI,
    provider: 'ollama',
  },
  {
    type: NodeType.HUBSPOT_CREATE_CONTACT,
    name: 'HubSpot: Create Contact',
    description: 'Create a contact in HubSpot CRM',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'hubspot',
  },
  {
    type: NodeType.HUBSPOT_CREATE_DEAL,
    name: 'HubSpot: Create Deal',
    description: 'Create a deal and optionally associate contacts',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'hubspot',
  },
  {
    type: NodeType.STRIPE_CREATE_CUSTOMER,
    name: 'Stripe: Create Customer',
    description: 'Create a Stripe customer with email, name, and metadata',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'stripe',
  },
  {
    type: NodeType.STRIPE_LIST_CHARGES,
    name: 'Stripe: List Charges',
    description: 'List recent Stripe charges, optionally filtered by customer',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'stripe',
  },
  {
    type: NodeType.MAILCHIMP_ADD_SUBSCRIBER,
    name: 'Mailchimp: Add Subscriber',
    description: 'Add a subscriber to a Mailchimp audience list',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'mailchimp',
  },
  {
    type: NodeType.MAILCHIMP_SEND_CAMPAIGN,
    name: 'Mailchimp: Send Campaign',
    description: 'Send a previously-created Mailchimp campaign',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'mailchimp',
  },
  {
    type: NodeType.CALENDLY_LIST_EVENTS,
    name: 'Calendly: List Scheduled Events',
    description: 'List Calendly events for a user, optionally within a time range',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'calendly',
  },
  {
    type: NodeType.POSTGRES_RUN_QUERY,
    name: 'Postgres: Run Parameterized Query',
    description: 'Run a parameterized SQL query against a Postgres database (no inline values)',
    category: NodeCategory.ACTION,
    group: NodeGroup.DATA,
    provider: 'postgres',
  },
  {
    type: NodeType.MYSQL_RUN_QUERY,
    name: 'MySQL: Run Parameterized Query',
    description: 'Run a parameterized SQL query against a MySQL database (no inline values)',
    category: NodeCategory.ACTION,
    group: NodeGroup.DATA,
    provider: 'mysql',
  },
  {
    type: NodeType.S3_UPLOAD_FILE,
    name: 'S3: Upload File',
    description: 'Upload an object to S3 / R2 / MinIO (streams large content via multipart)',
    category: NodeCategory.ACTION,
    group: NodeGroup.DATA,
    provider: 's3',
  },
  {
    type: NodeType.TRELLO_ADD_COMMENT,
    name: 'Trello: Add Comment',
    description: 'Post a comment on an existing Trello card',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'trello',
  },
  {
    type: NodeType.TRELLO_UPDATE_CARD,
    name: 'Trello: Update Card',
    description:
      'Update fields (name, description, due, list, archived) on an existing Trello card',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'trello',
  },
  {
    type: NodeType.STRIPE_EVENT_RECEIVED,
    name: 'Stripe: Event Received',
    description:
      'Trigger when a Stripe webhook event is delivered (HMAC-SHA256, 5-min replay window)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMERCE_TRIGGERS,
    provider: 'stripe',
  },
  {
    type: NodeType.HUBSPOT_CONTACT_CHANGED,
    name: 'HubSpot: Contact Changed',
    description:
      'Trigger when a HubSpot contact is created, updated, or deleted (push, X-HubSpot-Signature-v3)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMERCE_TRIGGERS,
    provider: 'hubspot',
  },
  {
    type: NodeType.MAILCHIMP_SUBSCRIBER_ADDED,
    name: 'Mailchimp: Subscriber Added',
    description: 'Trigger on Mailchimp audience events (subscribe / unsubscribe / cleaned)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMERCE_TRIGGERS,
    provider: 'mailchimp',
  },
  {
    type: NodeType.CALENDLY_EVENT_SCHEDULED,
    name: 'Calendly: Event Scheduled',
    description: 'Trigger when a Calendly invitee schedules or cancels an event (HMAC-SHA256)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMERCE_TRIGGERS,
    provider: 'calendly',
  },
  {
    type: NodeType.TRELLO_CARD_CHANGED,
    name: 'Trello: Card Changed',
    description: 'Trigger on Trello board events (create / update / comment / member changes)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMERCE_TRIGGERS,
    provider: 'trello',
  },
  // S15 — productivity & dev-tools read/update pack (#244)
  {
    type: NodeType.NOTION_GET_PAGE,
    name: 'Notion: Get Page',
    description: 'Retrieve a Notion page and its properties by ID',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'notion',
  },
  {
    type: NodeType.NOTION_UPDATE_PAGE,
    name: 'Notion: Update Page',
    description: 'Update a Notion page’s properties or archive/restore it',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'notion',
  },
  {
    type: NodeType.NOTION_APPEND_BLOCKS,
    name: 'Notion: Append Blocks',
    description: 'Append content blocks to a Notion page or block',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'notion',
  },
  {
    type: NodeType.NOTION_GET_BLOCK_CHILDREN,
    name: 'Notion: Get Block Children',
    description: 'Read the content blocks of a Notion page or block (paginated)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'notion',
  },
  {
    type: NodeType.NOTION_FIND_DATABASE_ITEM,
    name: 'Notion: Find Database Item',
    description: 'Query a Notion database and return the first matching item',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'notion',
  },
  {
    type: NodeType.TRELLO_GET_CARD,
    name: 'Trello: Get Card',
    description: 'Fetch a Trello card by ID',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'trello',
  },
  {
    type: NodeType.TRELLO_LIST_CARDS,
    name: 'Trello: List Cards',
    description: 'List cards on a Trello board or list',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'trello',
  },
  {
    type: NodeType.TRELLO_CREATE_LIST,
    name: 'Trello: Create List',
    description: 'Create a new list on a Trello board',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'trello',
  },
  {
    type: NodeType.AIRTABLE_GET_RECORD,
    name: 'Airtable: Get Record',
    description: 'Fetch a single Airtable record by ID',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'airtable',
  },
  {
    type: NodeType.AIRTABLE_FIND_RECORDS,
    name: 'Airtable: Find Records',
    description: 'Find Airtable records matching a filterByFormula expression',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'airtable',
  },
  {
    type: NodeType.AIRTABLE_DELETE_RECORD,
    name: 'Airtable: Delete Record',
    description: 'Delete a single Airtable record by ID',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'airtable',
  },
  {
    type: NodeType.LINEAR_GET_ISSUE,
    name: 'Linear: Get Issue',
    description: 'Fetch a Linear issue by ID',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'linear',
  },
  {
    type: NodeType.LINEAR_SEARCH_ISSUES,
    name: 'Linear: Search Issues',
    description: 'Search Linear issues by title text',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'linear',
  },
  {
    type: NodeType.LINEAR_ADD_COMMENT,
    name: 'Linear: Add Comment',
    description: 'Add a comment to a Linear issue',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'linear',
  },
  {
    type: NodeType.GITHUB_GET_ISSUE,
    name: 'GitHub: Get Issue',
    description: 'Fetch a GitHub issue by number',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_LIST_ISSUES,
    name: 'GitHub: List Issues',
    description: 'List issues in a GitHub repository (excludes pull requests)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_CLOSE_ISSUE,
    name: 'GitHub: Close Issue',
    description: 'Close an open GitHub issue',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_GET_REPO,
    name: 'GitHub: Get Repository',
    description: 'Fetch metadata for a GitHub repository',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_LIST_PRS,
    name: 'GitHub: List Pull Requests',
    description: 'List pull requests in a GitHub repository',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_MERGE_PR,
    name: 'GitHub: Merge Pull Request',
    description: 'Merge a GitHub pull request (merge / squash / rebase)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.NOTION_DATABASE_ITEM_UPDATED,
    name: 'Notion: Database Item Updated',
    description: 'Trigger when a Notion database item is edited (poll, last_edited_time cursor)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.PRODUCTIVITY_TRIGGERS,
    provider: 'notion',
  },
  {
    type: NodeType.AIRTABLE_RECORD_CREATED,
    name: 'Airtable: Record Created',
    description:
      'Trigger when a new record is added to an Airtable table (poll, createdTime cursor)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.PRODUCTIVITY_TRIGGERS,
    provider: 'airtable',
  },
  {
    type: NodeType.LINEAR_ISSUE_UPDATED,
    name: 'Linear: Issue Updated',
    description: 'Trigger when a Linear issue is created or updated (poll, updatedAt cursor)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.PRODUCTIVITY_TRIGGERS,
    provider: 'linear',
  },
  {
    type: NodeType.GITHUB_ISSUE_OPENED,
    name: 'GitHub: Issue Opened',
    description: 'Trigger when an issue is opened in a GitHub repo (webhook, X-Hub-Signature-256)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.PRODUCTIVITY_TRIGGERS,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_PR_OPENED,
    name: 'GitHub: Pull Request Opened',
    description:
      'Trigger when a pull request is opened in a GitHub repo (webhook, X-Hub-Signature-256)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.PRODUCTIVITY_TRIGGERS,
    provider: 'github',
  },
];
