import { NodeCategory, NodeGroup, NodeType, type NodeTypeDefinition } from '../node-enums.js';

export const GITHUB_NODES: NodeTypeDefinition[] = [
  {
    type: NodeType.GITHUB_CREATE_ISSUE,
    name: 'GitHub: Create Issue',
    description: 'Open a new issue in a GitHub repository',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_COMMENT_ISSUE,
    name: 'GitHub: Comment on Issue',
    description: 'Post a comment on a GitHub issue or pull request',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_CREATE_PR,
    name: 'GitHub: Create Pull Request',
    description: 'Open a pull request from one branch into another',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_GET_ISSUE,
    name: 'GitHub: Get Issue',
    description: 'Fetch a GitHub issue by number',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_LIST_ISSUES,
    name: 'GitHub: List Issues',
    description: 'List issues in a GitHub repository (excludes pull requests)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_CLOSE_ISSUE,
    name: 'GitHub: Close Issue',
    description: 'Close an open GitHub issue',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_GET_REPO,
    name: 'GitHub: Get Repository',
    description: 'Fetch metadata for a GitHub repository',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_LIST_PRS,
    name: 'GitHub: List Pull Requests',
    description: 'List pull requests in a GitHub repository',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_MERGE_PR,
    name: 'GitHub: Merge Pull Request',
    description: 'Merge a GitHub pull request (merge / squash / rebase)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_ISSUE_OPENED,
    name: 'GitHub: Issue Opened',
    description: 'Trigger when an issue is opened in a GitHub repo (webhook, X-Hub-Signature-256)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.PRODUCTIVITY_TRIGGERS,
    provider: 'github',
  },
  {
    type: NodeType.GITHUB_PR_OPENED,
    name: 'GitHub: Pull Request Opened',
    description:
      'Trigger when a pull request is opened in a GitHub repo (webhook, X-Hub-Signature-256)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.PRODUCTIVITY_TRIGGERS,
    provider: 'github',
  },
];
