import { NodeCategory, NodeGroup, NodeType, type NodeTypeDefinition } from '../node-enums.js';

export const GOOGLE_NODES: NodeTypeDefinition[] = [
  {
    type: NodeType.GMAIL_SEND,
    name: 'Gmail: Send Email',
    description: 'Send an email via Gmail',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_SEARCH,
    name: 'Gmail: Search Messages',
    description: 'Search Gmail messages with Gmail search syntax',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_GET_MESSAGE,
    name: 'Gmail: Get Message',
    description: 'Fetch a Gmail message by ID (headers, decoded body, attachment list)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_GET_ATTACHMENT,
    name: 'Gmail: Get Attachment',
    description: 'Download a Gmail attachment by message ID and attachment ID (base64)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_MODIFY_LABELS,
    name: 'Gmail: Modify Labels',
    description: 'Add/remove labels, archive, or mark a Gmail message read/unread',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_CREATE_DRAFT,
    name: 'Gmail: Create Draft',
    description: 'Create a Gmail draft (optionally a reply within a thread)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'google',
  },
  {
    type: NodeType.DRIVE_CREATE,
    name: 'Drive: Create File',
    description: 'Create a file in Google Drive',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DRIVE_LIST,
    name: 'Drive: List Files',
    description: 'List files in a Google Drive folder',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DRIVE_GET_FILE,
    name: 'Drive: Get File',
    description: 'Fetch Drive file metadata, with optional content download (base64)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_APPEND,
    name: 'Sheets: Append Row',
    description: 'Append a row of values to a Google Sheet',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_READ,
    name: 'Sheets: Read Range',
    description: 'Read a range from a Google Sheet (A1 notation)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_FIND_ROW,
    name: 'Sheets: Find Row',
    description: 'Find rows in a Google Sheet where a column equals a value',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_UPDATE_ROW,
    name: 'Sheets: Update Row',
    description: 'Overwrite a row in a Google Sheet by its row number',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_CLEAR_RANGE,
    name: 'Sheets: Clear Range',
    description: 'Clear all values in a range of a Google Sheet (A1 notation)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DOCS_CREATE,
    name: 'Docs: Create From Template',
    description: 'Copy a Google Doc template and replace placeholders',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DOCS_GET,
    name: 'Docs: Get Document',
    description: 'Read a Google Doc — title, plain text, and structural content',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DOCS_INSERT_TEXT,
    name: 'Docs: Insert Text',
    description: 'Insert text at an index in a Google Doc, or append to the end',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.DOCS_REPLACE_TEXT,
    name: 'Docs: Replace Text',
    description: 'Find and replace text tokens in a Google Doc (template fill)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.CALENDAR_CREATE,
    name: 'Calendar: Create Event',
    description: 'Create a Google Calendar event',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.CALENDAR_LIST_EVENTS,
    name: 'Calendar: List Events',
    description: 'List Google Calendar events in a time window',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.CALENDAR_GET_EVENT,
    name: 'Calendar: Get Event',
    description: 'Fetch a single Google Calendar event by ID',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_MESSAGE_RECEIVED,
    name: 'Gmail: Message Received',
    description:
      'Trigger when a new Gmail message arrives (poll by default; push via Cloud Pub/Sub when configured)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_LABEL_ADDED,
    name: 'Gmail: Label Added',
    description: 'Trigger when a label is added to a Gmail message (poll, historyId-based)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.GMAIL_ATTACHMENT_RECEIVED,
    name: 'Gmail: Attachment Received',
    description: 'Trigger when a new Gmail message arrives with an attachment (poll, historyId)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.DRIVE_FILE_ADDED,
    name: 'Drive: File Added',
    description: 'Trigger when a file is added to a Google Drive folder (push, watch channel)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.DRIVE_FILE_UPDATED,
    name: 'Drive: File Updated',
    description: 'Trigger when a watched Google Drive file is modified (push, watch channel)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.SHEETS_ROW_ADDED,
    name: 'Sheets: Row Added',
    description: 'Trigger when a new row is appended to a Google Sheet (poll, row-count cursor)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.CALENDAR_EVENT_CREATED,
    name: 'Calendar: Event Created',
    description: 'Trigger when a new event is created in a Google Calendar (poll, updatedMin)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
  {
    type: NodeType.CALENDAR_EVENT_UPDATED,
    name: 'Calendar: Event Updated',
    description:
      'Trigger when a Google Calendar event is changed or cancelled (poll, updated watermark)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.GOOGLE_TRIGGERS,
    provider: 'google',
  },
];
