import { NodeCategory, NodeGroup, NodeType, type NodeTypeDefinition } from '../node-enums.js';

export const MICROSOFT_NODES: NodeTypeDefinition[] = [
  {
    type: NodeType.OUTLOOK_SEND,
    name: 'Outlook: Send Email',
    description: 'Send an email via Outlook (Microsoft 365)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_SEARCH,
    name: 'Outlook: Search Inbox',
    description: 'Search Outlook messages with Microsoft Search syntax',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_GET_MESSAGE,
    name: 'Outlook: Get Message',
    description: 'Fetch a full Outlook message by ID (headers, body, attachment list)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_GET_ATTACHMENT,
    name: 'Outlook: Get Attachment',
    description: 'Download an Outlook attachment by message + attachment ID (base64)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_UPDATE_MESSAGE,
    name: 'Outlook: Update Message',
    description: 'Flag, categorize, mark read/unread, or move an Outlook message',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_CREATE_DRAFT,
    name: 'Outlook: Create Draft',
    description: 'Create a draft email, or a reply draft to an existing message',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_APPEND,
    name: 'Excel: Append Row',
    description: 'Append rows of values to an Excel Online worksheet',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_READ,
    name: 'Excel: Read Range',
    description: 'Read a range from an Excel Online worksheet (A1 notation)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_FIND_ROW,
    name: 'Excel: Find Row',
    description: 'Find table rows where a column matches a value (exact/contains/startsWith)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_UPDATE_ROW,
    name: 'Excel: Update Row',
    description: 'Overwrite an Excel table row by index or by a unique column lookup',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.ONEDRIVE_CREATE,
    name: 'OneDrive: Create File',
    description: 'Create a file in OneDrive',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.ONEDRIVE_GET_FILE,
    name: 'OneDrive: Get File',
    description: 'Fetch OneDrive file metadata and optionally download its content',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.ONEDRIVE_LIST_FILES,
    name: 'OneDrive: List Files',
    description: 'List items in a OneDrive folder (by id, path, or the drive root)',
    category: NodeCategory.ACTION,
    group: NodeGroup.PRODUCTIVITY,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_MESSAGE_RECEIVED,
    name: 'Outlook: Message Received',
    description:
      'Trigger when a new email arrives in the Outlook inbox (push, MS Graph subscription)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_MESSAGE_FLAGGED,
    name: 'Outlook: Message Flagged',
    description: 'Trigger when an Outlook message is flagged for follow-up (push, MS Graph)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
  {
    type: NodeType.ONEDRIVE_FILE_ADDED,
    name: 'OneDrive: File Added',
    description: 'Trigger when a file is added to OneDrive (push, MS Graph drive subscription)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_ROW_ADDED,
    name: 'Excel: Row Added',
    description:
      'Trigger when a new row is added to an Excel Online table (poll, row-index cursor)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
  {
    type: NodeType.EXCEL_ROW_UPDATED,
    name: 'Excel: Row Updated',
    description:
      'Trigger when an existing Excel Online table row changes (poll, per-row value hash)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
  {
    type: NodeType.OUTLOOK_MESSAGE_WITH_ATTACHMENT,
    name: 'Outlook: Message With Attachment',
    description:
      'Trigger when a new Outlook inbox message with attachments arrives (push, MS Graph subscription)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.MICROSOFT_TRIGGERS,
    provider: 'microsoft',
  },
];
