import { NodeCategory, NodeGroup, NodeType, type NodeTypeDefinition } from '../node-enums.js';

export const SLACK_NODES: NodeTypeDefinition[] = [
  {
    type: NodeType.SLACK_POST_MESSAGE,
    name: 'Slack: Post Message',
    description: 'Post a message to a Slack channel by ID (supports Block Kit blocks)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_POST_TO_CHANNEL,
    name: 'Slack: Post to Channel by Name',
    description: 'Look up a Slack channel by name and post a message',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_UPLOAD_FILE,
    name: 'Slack: Upload File',
    description: 'Upload a base64 file payload to a Slack channel',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_FIND_USER,
    name: 'Slack: Find User',
    description: 'Find a Slack user by email or by name',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_SEARCH_MESSAGES,
    name: 'Slack: Search Messages',
    description: 'Search Slack messages (requires a user token with search:read)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_ADD_REACTION,
    name: 'Slack: Add Reaction',
    description: 'Add an emoji reaction to a Slack message',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_CREATE_CHANNEL,
    name: 'Slack: Create Channel',
    description: 'Create a public or private Slack channel',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_INVITE_TO_CHANNEL,
    name: 'Slack: Invite to Channel',
    description: 'Invite one or more users to a Slack channel',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_GET_CHANNEL_HISTORY,
    name: 'Slack: Get Channel History',
    description: 'Read recent messages from a Slack channel',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_UPDATE_MESSAGE,
    name: 'Slack: Update Message',
    description: 'Edit a previously posted Slack message by timestamp',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMUNICATION,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_MESSAGE_RECEIVED,
    name: 'Slack: Message Received',
    description: 'Trigger when a message is posted to a Slack channel (push, Slack Events API)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMUNICATION_TRIGGERS,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_REACTION_ADDED,
    name: 'Slack: Reaction Added',
    description: 'Trigger when a reaction is added to a Slack message (push, Slack Events API)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMUNICATION_TRIGGERS,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_APP_MENTION,
    name: 'Slack: App Mention',
    description: 'Trigger when the app is @-mentioned in Slack (push, Slack Events API)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMUNICATION_TRIGGERS,
    provider: 'slack',
  },
  {
    type: NodeType.SLACK_CHANNEL_CREATED,
    name: 'Slack: Channel Created',
    description: 'Trigger when a new channel is created in the workspace (push, Slack Events API)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMUNICATION_TRIGGERS,
    provider: 'slack',
  },
];
