import { NodeCategory, NodeGroup, NodeType, type NodeTypeDefinition } from '../node-enums.js';

export const STRIPE_NODES: NodeTypeDefinition[] = [
  {
    type: NodeType.STRIPE_CREATE_CUSTOMER,
    name: 'Stripe: Create Customer',
    description: 'Create a Stripe customer with email, name, and metadata',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'stripe',
  },
  {
    type: NodeType.STRIPE_LIST_CHARGES,
    name: 'Stripe: List Charges',
    description: 'List recent Stripe charges, optionally filtered by customer',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'stripe',
  },
  {
    type: NodeType.STRIPE_EVENT_RECEIVED,
    name: 'Stripe: Event Received',
    description:
      'Trigger when a Stripe webhook event is delivered (HMAC-SHA256, 5-min replay window)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMERCE_TRIGGERS,
    provider: 'stripe',
  },
  {
    type: NodeType.STRIPE_GET_CUSTOMER,
    name: 'Stripe: Get Customer',
    description: 'Fetch a Stripe customer by ID',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'stripe',
  },
  {
    type: NodeType.STRIPE_FIND_CUSTOMER,
    name: 'Stripe: Find Customer',
    description: 'Find a Stripe customer by email address (search API)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'stripe',
  },
  {
    type: NodeType.STRIPE_CREATE_PAYMENT_INTENT,
    name: 'Stripe: Create Payment Intent',
    description: 'Create a Stripe PaymentIntent for a given amount and currency',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'stripe',
  },
  {
    type: NodeType.STRIPE_CREATE_REFUND,
    name: 'Stripe: Create Refund',
    description: 'Refund a Stripe payment intent or charge (full or partial)',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'stripe',
  },
  {
    type: NodeType.STRIPE_LIST_INVOICES,
    name: 'Stripe: List Invoices',
    description: 'List Stripe invoices, optionally filtered by customer or status',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'stripe',
  },
  {
    type: NodeType.STRIPE_CREATE_SUBSCRIPTION,
    name: 'Stripe: Create Subscription',
    description: 'Subscribe a customer to a recurring price',
    category: NodeCategory.ACTION,
    group: NodeGroup.COMMERCE,
    provider: 'stripe',
  },
  {
    type: NodeType.STRIPE_INVOICE_PAID,
    name: 'Stripe: Invoice Paid',
    description: 'Trigger when a Stripe invoice is paid (push, filtered invoice.paid event)',
    category: NodeCategory.TRIGGER,
    group: NodeGroup.COMMERCE_TRIGGERS,
    provider: 'stripe',
  },
];
